"""
原型Demo生成器
根据学习到的页面结构和样式生成可交互的原型HTML
"""

import json
from pathlib import Path
from typing import List, Dict, Optional, Any
from dataclasses import dataclass
from datetime import datetime


class PrototypeGenerator:
    """原型Demo生成器"""
    
    def __init__(self, page_structure_path: str):
        """
        初始化生成器
        
        Args:
            page_structure_path: 页面结构JSON文件路径
        """
        self.structure_path = Path(page_structure_path)
        self.page_structure = self._load_structure()
        
    def _load_structure(self) -> Dict:
        """加载页面结构"""
        if not self.structure_path.exists():
            return {}
        with open(self.structure_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    
    def generate(self, output_path: str, title: Optional[str] = None) -> str:
        """
        生成原型Demo HTML文件
        
        Args:
            output_path: 输出目录
            title: 页面标题
            
        Returns:
            生成的HTML文件路径
        """
        if not self.page_structure:
            print("[PrototypeGenerator] 没有页面结构数据")
            return ""
        
        page_title = title or self.page_structure.get('title', 'Prototype Demo')
        components = self.page_structure.get('components', [])
        layout_sections = self.page_structure.get('layout_sections', [])
        color_palette = self.page_structure.get('color_palette', [])
        typography = self.page_structure.get('typography', {})
        
        # 生成HTML
        html = self._generate_html(
            title=page_title,
            components=components,
            layout_sections=layout_sections,
            color_palette=color_palette,
            typography=typography
        )
        
        # 保存文件
        output_dir = Path(output_path)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        output_file = output_dir / f"prototype_{timestamp}.html"
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(html)
        
        print(f"[PrototypeGenerator] 原型Demo已生成: {output_file}")
        return str(output_file)
    
    def _generate_html(
        self,
        title: str,
        components: List[Dict],
        layout_sections: List[Dict],
        color_palette: List[str],
        typography: Dict
    ) -> str:
        """生成完整HTML"""
        
        # 生成CSS样式
        css = self._generate_css(color_palette, typography)
        
        # 生成组件HTML
        components_html = self._generate_components_html(components, layout_sections)
        
        # 生成交互脚本
        scripts = self._generate_scripts(components)
        
        html = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - 原型Demo</title>
    <style>
{css}
    </style>
</head>
<body>
    <div class="prototype-container">
        <div class="prototype-header">
            <h1>🎨 {title}</h1>
            <p class="prototype-meta">原型Demo | 基于Sentinel Learner生成</p>
        </div>
        
        <div class="prototype-content">
{components_html}
        </div>
        
        <div class="prototype-footer">
            <p>Generated by Sentinel Learner</p>
        </div>
    </div>
    
    <script>
{scripts}
    </script>
</body>
</html>'''
        
        return html
    
    def _generate_css(self, color_palette: List[str], typography: Dict) -> str:
        """生成CSS样式"""
        
        # 提取主色调
        primary_color = color_palette[0] if color_palette else '#1890ff'
        secondary_color = color_palette[1] if len(color_palette) > 1 else '#52c41a'
        bg_color = '#ffffff'
        text_color = '#333333'
        border_color = '#d9d9d9'
        
        # 字体大小
        font_sizes = typography.get('font_sizes', ['14px', '16px', '18px', '20px', '24px'])
        base_font_size = font_sizes[0] if font_sizes else '14px'
        
        css = f'''
/* 基础样式 */
* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    font-size: {base_font_size};
    line-height: 1.5;
    color: {text_color};
    background-color: #f5f5f5;
}}

/* 原型容器 */
.prototype-container {{
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
}}

.prototype-header {{
    background: linear-gradient(135deg, {primary_color} 0%, {secondary_color} 100%);
    color: white;
    padding: 30px;
    border-radius: 8px;
    margin-bottom: 30px;
}}

.prototype-header h1 {{
    font-size: 28px;
    margin-bottom: 10px;
}}

.prototype-meta {{
    opacity: 0.9;
    font-size: 14px;
}}

.prototype-content {{
    background: {bg_color};
    border-radius: 8px;
    padding: 30px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    min-height: 500px;
}}

.prototype-footer {{
    text-align: center;
    padding: 20px;
    color: #999;
    font-size: 12px;
}}

/* 布局区块 */
.layout-section {{
    margin-bottom: 30px;
    padding: 20px;
    border: 1px dashed {border_color};
    border-radius: 6px;
    position: relative;
}}

.layout-section::before {{
    content: attr(data-label);
    position: absolute;
    top: -10px;
    left: 10px;
    background: {bg_color};
    padding: 0 10px;
    font-size: 12px;
    color: #999;
}}

/* 组件样式 */
.comp-button {{
    display: inline-block;
    padding: 8px 16px;
    background: {primary_color};
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.3s;
    margin: 5px;
}}

.comp-button:hover {{
    opacity: 0.8;
    transform: translateY(-1px);
}}

.comp-input {{
    display: block;
    width: 100%;
    max-width: 300px;
    padding: 8px 12px;
    border: 1px solid {border_color};
    border-radius: 4px;
    font-size: 14px;
    margin: 5px 0;
}}

.comp-input:focus {{
    outline: none;
    border-color: {primary_color};
    box-shadow: 0 0 0 2px rgba(24,144,255,0.2);
}}

.comp-select {{
    display: block;
    width: 100%;
    max-width: 300px;
    padding: 8px 12px;
    border: 1px solid {border_color};
    border-radius: 4px;
    font-size: 14px;
    background: white;
    margin: 5px 0;
}}

.comp-card {{
    background: white;
    border: 1px solid {border_color};
    border-radius: 8px;
    padding: 20px;
    margin: 10px 0;
    box-shadow: 0 2px 4px rgba(0,0,0,0.05);
}}

.comp-menu {{
    display: flex;
    list-style: none;
    background: white;
    border-bottom: 1px solid {border_color};
    padding: 0;
}}

.comp-menu li {{
    padding: 12px 20px;
    cursor: pointer;
    border-bottom: 2px solid transparent;
    transition: all 0.3s;
}}

.comp-menu li:hover,
.comp-menu li.active {{
    color: {primary_color};
    border-bottom-color: {primary_color};
}}

.comp-table {{
    width: 100%;
    border-collapse: collapse;
    margin: 10px 0;
}}

.comp-table th,
.comp-table td {{
    padding: 12px;
    text-align: left;
    border-bottom: 1px solid {border_color};
}}

.comp-table th {{
    background: #fafafa;
    font-weight: 600;
}}

.comp-list {{
    list-style: none;
    padding: 0;
}}

.comp-list li {{
    padding: 10px;
    border-bottom: 1px solid #f0f0f0;
}}

.comp-list li:last-child {{
    border-bottom: none;
}}

.comp-modal {{
    display: none;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.5);
    z-index: 1000;
    justify-content: center;
    align-items: center;
}}

.comp-modal.active {{
    display: flex;
}}

.comp-modal-content {{
    background: white;
    padding: 30px;
    border-radius: 8px;
    max-width: 500px;
    width: 90%;
}}

.comp-tabs {{
    display: flex;
    border-bottom: 1px solid {border_color};
    margin-bottom: 20px;
}}

.comp-tab {{
    padding: 10px 20px;
    cursor: pointer;
    border-bottom: 2px solid transparent;
}}

.comp-tab.active {{
    color: {primary_color};
    border-bottom-color: {primary_color};
}}

.comp-search {{
    display: flex;
    max-width: 400px;
}}

.comp-search input {{
    flex: 1;
    padding: 8px 12px;
    border: 1px solid {border_color};
    border-right: none;
    border-radius: 4px 0 0 4px;
}}

.comp-search button {{
    padding: 8px 16px;
    background: {primary_color};
    color: white;
    border: none;
    border-radius: 0 4px 4px 0;
    cursor: pointer;
}}

.comp-checkbox,
.comp-radio {{
    display: flex;
    align-items: center;
    margin: 8px 0;
    cursor: pointer;
}}

.comp-checkbox input,
.comp-radio input {{
    margin-right: 8px;
}}

.comp-alert {{
    padding: 12px 16px;
    border-radius: 4px;
    margin: 10px 0;
}}

.comp-alert.info {{
    background: #e6f7ff;
    border: 1px solid #91d5ff;
    color: #096dd9;
}}

.comp-alert.success {{
    background: #f6ffed;
    border: 1px solid #b7eb8f;
    color: #389e0d;
}}

.comp-alert.warning {{
    background: #fffbe6;
    border: 1px solid #ffe58f;
    color: #d48806;
}}

.comp-alert.error {{
    background: #fff2f0;
    border: 1px solid #ffccc7;
    color: #cf1322;
}}

/* 响应式 */
@media (max-width: 768px) {{
    .prototype-container {{
        padding: 10px;
    }}
    
    .prototype-content {{
        padding: 15px;
    }}
    
    .comp-menu {{
        flex-wrap: wrap;
    }}
}}
'''
        return css
    
    def _generate_components_html(
        self,
        components: List[Dict],
        layout_sections: List[Dict]
    ) -> str:
        """生成组件HTML"""
        
        if not components:
            return '<p class="placeholder">暂无组件数据</p>'
        
        html_parts = []
        
        # 按布局区块组织组件
        if layout_sections:
            for section in layout_sections:
                section_type = section.get('type', 'unknown')
                section_name = section.get('name', section_type)
                component_ids = section.get('component_ids', [])
                
                section_html = f'        <div class="layout-section" data-label="{section_name}">\n'
                
                # 找到属于该区块的组件
                for comp in components:
                    if comp.get('id') in component_ids:
                        comp_html = self._render_component(comp)
                        section_html += f'          {comp_html}\n'
                
                section_html += '        </div>'
                html_parts.append(section_html)
        else:
            # 没有布局区块，直接渲染所有组件
            for comp in components:
                comp_html = self._render_component(comp)
                html_parts.append(f'        <div class="component-wrapper">\n          {comp_html}\n        </div>')
        
        return '\n'.join(html_parts)
    
    def _render_component(self, component: Dict) -> str:
        """渲染单个组件"""
        comp_type = component.get('type', 'unknown')
        text = component.get('text_content', '')
        attributes = component.get('attributes', {})
        placeholder = component.get('placeholder', '')
        
        # 根据组件类型渲染
        type_map = {
            'button': self._render_button,
            'input': self._render_input,
            'select': self._render_select,
            'checkbox': self._render_checkbox,
            'radio': self._render_radio,
            'menu': self._render_menu,
            'modal': self._render_modal,
            'tabs': self._render_tabs,
            'search': self._render_search,
            'table': self._render_table,
            'list': self._render_list,
            'card': self._render_card,
            'alert': self._render_alert,
        }
        
        render_func = type_map.get(comp_type, self._render_generic)
        return render_func(component)
    
    def _render_button(self, component: Dict) -> str:
        text = component.get('text_content', '按钮')
        return f'<button class="comp-button">{text}</button>'
    
    def _render_input(self, component: Dict) -> str:
        attrs = component.get('attributes', {})
        input_type = attrs.get('type', 'text')
        placeholder = attrs.get('placeholder', '请输入...')
        return f'<input type="{input_type}" class="comp-input" placeholder="{placeholder}">'
    
    def _render_select(self, component: Dict) -> str:
        options = ['<option>请选择</option>', '<option>选项1</option>', '<option>选项2</option>']
        return f'<select class="comp-select">{ "".join(options) }</select>'
    
    def _render_checkbox(self, component: Dict) -> str:
        text = component.get('text_content', '选项')
        return f'<label class="comp-checkbox"><input type="checkbox"> {text}</label>'
    
    def _render_radio(self, component: Dict) -> str:
        text = component.get('text_content', '选项')
        return f'<label class="comp-radio"><input type="radio" name="radio-group"> {text}</label>'
    
    def _render_menu(self, component: Dict) -> str:
        items = ['首页', '产品', '关于', '联系']
        lis = ''.join([f'<li>{item}</li>' for item in items])
        return f'<ul class="comp-menu">{lis}</ul>'
    
    def _render_modal(self, component: Dict) -> str:
        return '''
        <div class="comp-modal" id="modal-demo">
            <div class="comp-modal-content">
                <h3>模态框标题</h3>
                <p>这是一个模态框内容示例。</p>
                <button class="comp-button" onclick="closeModal()">关闭</button>
            </div>
        </div>
        <button class="comp-button" onclick="openModal()">打开模态框</button>
        '''
    
    def _render_tabs(self, component: Dict) -> str:
        tabs = ['Tab 1', 'Tab 2', 'Tab 3']
        tab_html = ''.join([f'<div class="comp-tab{ " active" if i==0 else ""}">{tab}</div>' for i, tab in enumerate(tabs)])
        return f'<div class="comp-tabs">{tab_html}</div>'
    
    def _render_search(self, component: Dict) -> str:
        return '''
        <div class="comp-search">
            <input type="text" placeholder="搜索...">
            <button>搜索</button>
        </div>
        '''
    
    def _render_table(self, component: Dict) -> str:
        return '''
        <table class="comp-table">
            <thead>
                <tr><th>列1</th><th>列2</th><th>列3</th></tr>
            </thead>
            <tbody>
                <tr><td>数据1</td><td>数据2</td><td>数据3</td></tr>
                <tr><td>数据4</td><td>数据5</td><td>数据6</td></tr>
            </tbody>
        </table>
        '''
    
    def _render_list(self, component: Dict) -> str:
        items = ['列表项 1', '列表项 2', '列表项 3']
        lis = ''.join([f'<li>{item}</li>' for item in items])
        return f'<ul class="comp-list">{lis}</ul>'
    
    def _render_card(self, component: Dict) -> str:
        return '''
        <div class="comp-card">
            <h4>卡片标题</h4>
            <p>这是卡片内容描述...</p>
            <button class="comp-button">了解更多</button>
        </div>
        '''
    
    def _render_alert(self, component: Dict) -> str:
        return '<div class="comp-alert info">提示信息</div>'
    
    def _render_generic(self, component: Dict) -> str:
        """通用渲染"""
        tag = component.get('tag', 'div')
        text = component.get('text_content', '')
        if text:
            return f'<{tag}>{text}</{tag}>'
        return f'<{tag}></{tag}>'
    
    def _generate_scripts(self, components: List[Dict]) -> str:
        """生成交互脚本"""
        
        scripts = '''
// 原型Demo交互脚本

// 模态框控制
function openModal() {
    document.getElementById('modal-demo').classList.add('active');
}

function closeModal() {
    document.getElementById('modal-demo').classList.remove('active');
}

// Tab切换
document.querySelectorAll('.comp-tab').forEach(tab => {
    tab.addEventListener('click', function() {
        document.querySelectorAll('.comp-tab').forEach(t => t.classList.remove('active'));
        this.classList.add('active');
    });
});

// 按钮点击效果
document.querySelectorAll('.comp-button').forEach(btn => {
    btn.addEventListener('click', function(e) {
        // 添加点击动画
        this.style.transform = 'scale(0.95)';
        setTimeout(() => {
            this.style.transform = '';
        }, 100);
        
        console.log('点击了:', this.textContent);
    });
});

// 输入框焦点效果
document.querySelectorAll('.comp-input').forEach(input => {
    input.addEventListener('focus', function() {
        console.log('聚焦输入框:', this.placeholder);
    });
});

console.log('🎨 原型Demo已加载');
console.log('📊 组件数量: ''' + str(len(components)) + '''');
'''
        return scripts


def generate_prototype_from_task(task_path: str, output_dir: str) -> str:
    """
    从任务目录生成原型Demo
    
    Args:
        task_path: 任务目录路径
        output_dir: 输出目录
        
    Returns:
        生成的HTML文件路径
    """
    task_dir = Path(task_path)
    
    # 查找页面结构文件
    structure_file = task_dir / 'output' / 'page_structure.json'
    
    if not structure_file.exists():
        # 尝试从DOM snapshot提取
        dom_files = list(task_dir.glob('dom/snapshot_*.json'))
        if dom_files:
            from ..extractors.page_structure_extractor import PageStructureExtractor
            extractor = PageStructureExtractor(str(dom_files[0]))
            extractor.save(task_dir / 'output')
            structure_file = task_dir / 'output' / 'page_structure.json'
    
    if not structure_file.exists():
        print(f"[PrototypeGenerator] 未找到页面结构数据: {task_path}")
        return ""
    
    # 生成原型
    generator = PrototypeGenerator(str(structure_file))
    return generator.generate(output_dir)
